name: Release to QA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd /application/html/nuxt-demo/nuxt-demo1
          rm -rf aaa
